version: '3'

services:
  db:
    image: postgres:11
    env_file:
      - database.env
    ports: 
      - 5432:5432

  script_runner:
    image: postgres:11
    env_file:
      - database.env
    depends_on:
      - db
    volumes:
      - ./sql_code:/sql_code
    command:
      - /bin/bash
      - sql_code/entrypoint.sh
    ports: 
      - 8080:80
